import XCTest
import CoreGraphics
@testable import LockIn

/// Perceptual regression: does any clip *look* different from the last time
/// this was reviewed?
///
/// The other stick-figure tests assert geometry — lengths, contacts, ordering.
/// A change can satisfy all of them and still be a visual regression, which is
/// exactly the class of bug that needed a human squinting at contact sheets to
/// catch. Comparing a coarse render against a recorded fingerprint automates
/// the squinting.
final class StickFigureSignatureTests: XCTestCase {

    /// How far a clip may drift before it counts as a visual change.
    ///
    /// Calibrated, not guessed: an untouched clip scores 0.0, and bending the
    /// plank's knee by seven degrees — about the subtlest edit worth failing
    /// on — scores 13.4. Sitting at 6 leaves room for rasteriser differences
    /// while still catching that.
    private let tolerance = 6.0

    func testNoClipHasChangedItsAppearance() throws {
        var drifted: [(String, Double)] = []
        var missing: [String] = []

        for pattern in MovementPattern.allCases {
            let now = StickFigureSignature.signature(of: pattern)
            XCTAssertFalse(now.isEmpty, "\(pattern.rawValue) rendered nothing")

            guard let recorded = StickFigureBaseline.signatures[pattern.rawValue] else {
                missing.append(pattern.rawValue)
                continue
            }
            let distance = StickFigureSignature.distance(now, StickFigureSignature.decode(recorded))
            if distance > tolerance { drifted.append((pattern.rawValue, distance)) }
        }

        if !missing.isEmpty || !drifted.isEmpty {
            // Write the current state next to the test results so an
            // intentional change can be reviewed and pasted in, rather than
            // leaving someone to reconstruct 33 fingerprints by hand.
            try dumpCurrentBaseline()
        }
        XCTAssertTrue(missing.isEmpty, "No recorded appearance for: \(missing.joined(separator: ", "))")
        XCTAssertTrue(
            drifted.isEmpty,
            "Clips changed appearance: " +
            drifted.map { "\($0.0) (\(String(format: "%.1f", $0.1)))" }.joined(separator: ", ") +
            " — if deliberate, replace StickFigureBaseline with the regenerated file."
        )
    }

    /// Two different movements must not produce the same picture. Guards the
    /// fingerprint itself: a signature that collapses everything to the same
    /// value would make the test above pass unconditionally.
    func testSignatureTellsDifferentClipsApart() {
        let squat = StickFigureSignature.signature(of: .squat)
        let plank = StickFigureSignature.signature(of: .plank)
        XCTAssertGreaterThan(
            StickFigureSignature.distance(squat, plank), 12,
            "signature can't tell a squat from a plank — it isn't measuring anything"
        )
    }

    private func dumpCurrentBaseline() throws {
        var lines = [
            "// Regenerated by StickFigureSignatureTests.",
            "enum StickFigureBaseline {",
            "    static let signatures: [String: String] = ["
        ]
        for pattern in MovementPattern.allCases {
            let encoded = StickFigureSignature.encode(StickFigureSignature.signature(of: pattern))
            lines.append("        \"\(pattern.rawValue)\": \"\(encoded)\",")
        }
        lines.append("    ]")
        lines.append("}")

        let url = FileManager.default.temporaryDirectory
            .appendingPathComponent("StickFigureBaseline.swift")
        try lines.joined(separator: "\n").write(to: url, atomically: true, encoding: .utf8)
        print("REGENERATED BASELINE AT: \(url.path)")
    }
}
